POST http://localhost:3000/api/signin
Content-Type: application/json

{
    "email" : "fikri@gmail.com",
    "password" : "Test1234" 
}

###
GET http://localhost:3000/api/cek-login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZmlrcmlAZ21haWwuY29tIiwiaWF0IjoxNzA1ODQ0NTAwLCJleHAiOjE3MDU4NDQ1MjB9.azJmyNXT_JSNbKS6K08AXVmM_-7-qpH4FZKKJs6xub8

###
GET http://localhost:3000/api/token

###
DELETE http://localhost:3000/api/logout

###
GET http://localhost:3000/api/get-films

###
GET http://localhost:3000/api/get-films-by-schedule
Content-Type: application/json

{ "film_id":1, "date":"21", "time_id":2 }

###
GET http://localhost:3000/api/get-films-filter-bioskop
Content-Type: application/json

{ "bioskop": "cgv" }

###
GET http://localhost:3000/api/get-malls

###
GET http://localhost:3000/api/get-user-ticket
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZmlrcmlAZ21haWwuY29tIiwiaWF0IjoxNzA1ODQ0NjEwLCJleHAiOjE3MDU4NDQ2MjV9.MycQ5ahfWQmlaihO7kr015Xn1-Eq9mMzG6Yvf2TipRA